// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn0jMJzaNhTm0bgkG5s1LwJjMa9V-ntLc',
    appId: '1:1053897309653:web:4202a0d52c35ad6fbd515c',
    messagingSenderId: '1053897309653',
    projectId: 'ebook-reader-app-68d6e',
    authDomain: 'ebook-reader-app-68d6e.firebaseapp.com',
    storageBucket: 'ebook-reader-app-68d6e.firebasestorage.app',
    measurementId: 'G-PNN9ZTEDJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdr15SrcgOtWbG9bCj1CO49knXtvh5UtA',
    appId: '1:1053897309653:android:536f057e153a00ddbd515c',
    messagingSenderId: '1053897309653',
    projectId: 'ebook-reader-app-68d6e',
    storageBucket: 'ebook-reader-app-68d6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEewjGVUkRzRpt4YLDXWYQkq9qQ3gsDs',
    appId: '1:1053897309653:ios:4907a552d41ce7a2bd515c',
    messagingSenderId: '1053897309653',
    projectId: 'ebook-reader-app-68d6e',
    storageBucket: 'ebook-reader-app-68d6e.firebasestorage.app',
    iosBundleId: 'com.wildbuster.ebookReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbEewjGVUkRzRpt4YLDXWYQkq9qQ3gsDs',
    appId: '1:1053897309653:ios:4907a552d41ce7a2bd515c',
    messagingSenderId: '1053897309653',
    projectId: 'ebook-reader-app-68d6e',
    storageBucket: 'ebook-reader-app-68d6e.firebasestorage.app',
    iosBundleId: 'com.wildbuster.ebookReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn0jMJzaNhTm0bgkG5s1LwJjMa9V-ntLc',
    appId: '1:1053897309653:web:74ef348bb37180a8bd515c',
    messagingSenderId: '1053897309653',
    projectId: 'ebook-reader-app-68d6e',
    authDomain: 'ebook-reader-app-68d6e.firebaseapp.com',
    storageBucket: 'ebook-reader-app-68d6e.firebasestorage.app',
    measurementId: 'G-MV5LLVZYG4',
  );
}
